/**
 * Customer Seeder
 * Creates B2B and B2C customers with realistic data
 */

import Customer from '../models_temp/Customer';
import { CustomerType } from '../types/models';
import logger from '../utils/logger';

/**
 * Seed customers into the database
 */
export const seedCustomers = async (): Promise<void> => {
  try {
    // Check if customers already exist
    const existingCount = await Customer.countDocuments();
    if (existingCount > 0) {
      logger.info(`Customers already exist (${existingCount} found). Skipping customer seeding.`);
      return;
    }

    const customers = [
      // B2B Customers
      {
        name: 'TechCorp Solutions Inc.',
        code: 'CUST-B2B-001',
        type: CustomerType.B2B,
        email: 'purchasing@techcorp.com',
        phone: '+1-555-2001',
        contactPerson: 'Alex Thompson',
        address: '456 Enterprise Way',
        city: 'San Jose',
        state: 'CA',
        country: 'USA',
        zipCode: '95110',
        taxId: 'TC-789456123',
        creditLimit: 50000,
        creditBalance: 12500,
        paymentTerms: 'Net 30',
        loyaltyPoints: 2500,
        isActive: true,
      },
      {
        name: 'Global Manufacturing Ltd.',
        code: 'CUST-B2B-002',
        type: CustomerType.B2B,
        email: 'orders@globalmanufacturing.com',
        phone: '+1-555-2002',
        contactPerson: 'Rebecca Foster',
        address: '789 Industrial Blvd',
        city: 'Detroit',
        state: 'MI',
        country: 'USA',
        zipCode: '48201',
        taxId: 'GM-456789321',
        creditLimit: 75000,
        creditBalance: 18750,
        paymentTerms: 'Net 45',
        loyaltyPoints: 3800,
        isActive: true,
      },
      {
        name: 'Retail Giants Inc.',
        code: 'CUST-B2B-003',
        type: CustomerType.B2B,
        email: 'procurement@retailgiants.com',
        phone: '+1-555-2003',
        contactPerson: 'Marcus Johnson',
        address: '321 Commerce Street',
        city: 'Atlanta',
        state: 'GA',
        country: 'USA',
        zipCode: '30301',
        taxId: 'RG-321654987',
        creditLimit: 100000,
        creditBalance: 45000,
        paymentTerms: 'Net 60',
        loyaltyPoints: 5200,
        isActive: true,
      },
      {
        name: 'Healthcare Partners LLC',
        code: 'CUST-B2B-004',
        type: CustomerType.B2B,
        email: 'supplies@healthcarepartners.com',
        phone: '+1-555-2004',
        contactPerson: 'Dr. Emily Roberts',
        address: '654 Medical Plaza',
        city: 'Boston',
        state: 'MA',
        country: 'USA',
        zipCode: '02108',
        taxId: 'HP-654987321',
        creditLimit: 60000,
        creditBalance: 22000,
        paymentTerms: 'Net 30',
        loyaltyPoints: 2900,
        isActive: true,
      },
      {
        name: 'Education Systems Group',
        code: 'CUST-B2B-005',
        type: CustomerType.B2B,
        email: 'purchasing@edusystems.com',
        phone: '+1-555-2005',
        contactPerson: 'Patricia Moore',
        address: '987 Campus Drive',
        city: 'Austin',
        state: 'TX',
        country: 'USA',
        zipCode: '78701',
        taxId: 'ES-987321654',
        creditLimit: 40000,
        creditBalance: 8500,
        paymentTerms: 'Net 45',
        loyaltyPoints: 1800,
        isActive: true,
      },
      {
        name: 'Construction Builders Co.',
        code: 'CUST-B2B-006',
        type: CustomerType.B2B,
        email: 'materials@constructionbuilders.com',
        phone: '+1-555-2006',
        contactPerson: 'James Wilson',
        address: '147 Builder Lane',
        city: 'Phoenix',
        state: 'AZ',
        country: 'USA',
        zipCode: '85001',
        taxId: 'CB-147258369',
        creditLimit: 80000,
        creditBalance: 35000,
        paymentTerms: 'Net 60',
        loyaltyPoints: 4100,
        isActive: true,
      },
      {
        name: 'Restaurant Supply Chain',
        code: 'CUST-B2B-007',
        type: CustomerType.B2B,
        email: 'orders@restaurantsupply.com',
        phone: '+1-555-2007',
        contactPerson: 'Maria Gonzalez',
        address: '258 Culinary Ave',
        city: 'Las Vegas',
        state: 'NV',
        country: 'USA',
        zipCode: '89101',
        taxId: 'RS-258369147',
        creditLimit: 45000,
        creditBalance: 15000,
        paymentTerms: 'Net 30',
        loyaltyPoints: 2200,
        isActive: true,
      },
      {
        name: 'Office Space Rentals',
        code: 'CUST-B2B-008',
        type: CustomerType.B2B,
        email: 'facilities@officespacerentals.com',
        phone: '+1-555-2008',
        contactPerson: 'Christopher Lee',
        address: '369 Office Park',
        city: 'Denver',
        state: 'CO',
        country: 'USA',
        zipCode: '80201',
        taxId: 'OR-369147258',
        creditLimit: 55000,
        creditBalance: 20000,
        paymentTerms: 'Net 45',
        loyaltyPoints: 2700,
        isActive: true,
      },
      {
        name: 'Logistics Solutions Inc.',
        code: 'CUST-B2B-009',
        type: CustomerType.B2B,
        email: 'operations@logisticssolutions.com',
        phone: '+1-555-2009',
        contactPerson: 'Daniel Brown',
        address: '741 Transport Blvd',
        city: 'Memphis',
        state: 'TN',
        country: 'USA',
        zipCode: '38101',
        taxId: 'LS-741852963',
        creditLimit: 70000,
        creditBalance: 28000,
        paymentTerms: 'Net 30',
        loyaltyPoints: 3400,
        isActive: true,
      },
      {
        name: 'Government Services Agency',
        code: 'CUST-B2B-010',
        type: CustomerType.B2B,
        email: 'procurement@govservices.gov',
        phone: '+1-555-2010',
        contactPerson: 'Michelle Davis',
        address: '852 Government Plaza',
        city: 'Washington',
        state: 'DC',
        country: 'USA',
        zipCode: '20001',
        taxId: 'GS-852963741',
        creditLimit: 150000,
        creditBalance: 75000,
        paymentTerms: 'Net 60',
        loyaltyPoints: 6500,
        isActive: true,
      },

      // B2C Customers
      {
        name: 'John Anderson',
        code: 'CUST-B2C-001',
        type: CustomerType.B2C,
        email: 'john.anderson@email.com',
        phone: '+1-555-3001',
        address: '123 Maple Street',
        city: 'Portland',
        state: 'OR',
        country: 'USA',
        zipCode: '97201',
        creditLimit: 5000,
        creditBalance: 850,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 450,
        isActive: true,
      },
      {
        name: 'Sarah Mitchell',
        code: 'CUST-B2C-002',
        type: CustomerType.B2C,
        email: 'sarah.mitchell@email.com',
        phone: '+1-555-3002',
        address: '456 Oak Avenue',
        city: 'Seattle',
        state: 'WA',
        country: 'USA',
        zipCode: '98101',
        creditLimit: 3000,
        creditBalance: 0,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 720,
        isActive: true,
      },
      {
        name: 'Michael Chen',
        code: 'CUST-B2C-003',
        type: CustomerType.B2C,
        email: 'michael.chen@email.com',
        phone: '+1-555-3003',
        address: '789 Pine Road',
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
        zipCode: '94102',
        creditLimit: 4000,
        creditBalance: 1200,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 890,
        isActive: true,
      },
      {
        name: 'Emily Johnson',
        code: 'CUST-B2C-004',
        type: CustomerType.B2C,
        email: 'emily.johnson@email.com',
        phone: '+1-555-3004',
        address: '321 Elm Street',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        zipCode: '10001',
        creditLimit: 2500,
        creditBalance: 450,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 320,
        isActive: true,
      },
      {
        name: 'David Martinez',
        code: 'CUST-B2C-005',
        type: CustomerType.B2C,
        email: 'david.martinez@email.com',
        phone: '+1-555-3005',
        address: '654 Birch Lane',
        city: 'Miami',
        state: 'FL',
        country: 'USA',
        zipCode: '33101',
        creditLimit: 3500,
        creditBalance: 750,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 560,
        isActive: true,
      },
      {
        name: 'Jennifer Wilson',
        code: 'CUST-B2C-006',
        type: CustomerType.B2C,
        email: 'jennifer.wilson@email.com',
        phone: '+1-555-3006',
        address: '987 Cedar Court',
        city: 'Chicago',
        state: 'IL',
        country: 'USA',
        zipCode: '60601',
        creditLimit: 4500,
        creditBalance: 1500,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 1020,
        isActive: true,
      },
      {
        name: 'Robert Taylor',
        code: 'CUST-B2C-007',
        type: CustomerType.B2C,
        email: 'robert.taylor@email.com',
        phone: '+1-555-3007',
        address: '147 Spruce Drive',
        city: 'Houston',
        state: 'TX',
        country: 'USA',
        zipCode: '77001',
        creditLimit: 3000,
        creditBalance: 0,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 680,
        isActive: true,
      },
      {
        name: 'Amanda White',
        code: 'CUST-B2C-008',
        type: CustomerType.B2C,
        email: 'amanda.white@email.com',
        phone: '+1-555-3008',
        address: '258 Willow Way',
        city: 'Phoenix',
        state: 'AZ',
        country: 'USA',
        zipCode: '85001',
        creditLimit: 2000,
        creditBalance: 350,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 290,
        isActive: true,
      },
      {
        name: 'Christopher Lee',
        code: 'CUST-B2C-009',
        type: CustomerType.B2C,
        email: 'christopher.lee@email.com',
        phone: '+1-555-3009',
        address: '369 Poplar Place',
        city: 'Philadelphia',
        state: 'PA',
        country: 'USA',
        zipCode: '19101',
        creditLimit: 5000,
        creditBalance: 2000,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 1350,
        isActive: true,
      },
      {
        name: 'Lisa Brown',
        code: 'CUST-B2C-010',
        type: CustomerType.B2C,
        email: 'lisa.brown@email.com',
        phone: '+1-555-3010',
        address: '741 Ash Boulevard',
        city: 'San Diego',
        state: 'CA',
        country: 'USA',
        zipCode: '92101',
        creditLimit: 3500,
        creditBalance: 900,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 740,
        isActive: true,
      },
      {
        name: 'Kevin Anderson',
        code: 'CUST-B2C-011',
        type: CustomerType.B2C,
        email: 'kevin.anderson@email.com',
        phone: '+1-555-3011',
        address: '852 Cherry Street',
        city: 'Dallas',
        state: 'TX',
        country: 'USA',
        zipCode: '75201',
        creditLimit: 4000,
        creditBalance: 1100,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 820,
        isActive: true,
      },
      {
        name: 'Nicole Thomas',
        code: 'CUST-B2C-012',
        type: CustomerType.B2C,
        email: 'nicole.thomas@email.com',
        phone: '+1-555-3012',
        address: '963 Walnut Avenue',
        city: 'San Antonio',
        state: 'TX',
        country: 'USA',
        zipCode: '78201',
        creditLimit: 2500,
        creditBalance: 500,
        paymentTerms: 'Due on Receipt',
        loyaltyPoints: 430,
        isActive: true,
      },
    ];

    const createdCustomers = await Customer.insertMany(customers);
    logger.info(`✓ Created ${createdCustomers.length} customers (${customers.filter(c => c.type === CustomerType.B2B).length} B2B, ${customers.filter(c => c.type === CustomerType.B2C).length} B2C)`);
  } catch (error) {
    logger.error('Error seeding customers:', error);
    throw error;
  }
};

/**
 * Clear all customers from the database
 */
export const clearCustomers = async (): Promise<void> => {
  try {
    await Customer.deleteMany({});
    logger.info('✓ Cleared all customers');
  } catch (error) {
    logger.error('Error clearing customers:', error);
    throw error;
  }
};
